# Dependencies
markdown:         kramdown

# Permalinks
permalink:        :title

# Setup
title:            Tiny Quark
tagline:          'We build great stuff.'
baseurl:          /
destination:      ./build

author:
  name:           'Bryan Schuetz'
  url:            http://distresssignal.org

# Custom vars
version: 1.0

# Sass support via Jekyll 2.0
sass:
  sass_dir:     assets/_sass
# Set baseurl for gh-pages
baseurl: ""
