# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Tiny Quark
tagline:          'A tagline place holder. The real tagline can go here.'
baseurl:          /
destination:      ./build

author:
  name:           'Bryan Schuetz'
  url:            http://distresssignal.org

paginate:         5

# Custom vars
version: 1.0

# Sass support via Jekyll 2.0
sass:
  sass_dir:     assets/_sass
# Set baseurl for gh-pages
baseurl: ""
